version: '3'
services:
  db:
    image: postgres
    networks:
      - foo
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    tty: true
    stdin_open: true
    build: .
    networks:
      - foo
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    networks:
      - foo
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq

  redis:
    image: redis
    command: redis-server
    networks:
      - foo
    ports:
      - "6379"

networks:
  foo:
